apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dev
type: Opaque
data:
  user_name: bXl1c2Vy        # 'mysql' base64 encoded
  password: bXl1c2VyQDEyMw== # 'mysql@123' base64 encoded
